### PR TITLE
changing the accountid and userid resolving

### LINKED ISSUE #16: Can't login when my user has accounts in multiple Data centers
After the activation of the device I am getting this error: "authentication failed. missing key accountId. did your run gtmhub login?"

### PR DESCRIPTION
**Pull request by petarpetkov**
closes #16

### CODE REVIEW

File: commands/login.go [hunk 1]
```diff
@@ -64,22 +64,17 @@ func LoginAction(c *cli.Context) error {
 
 	config.SetRefreshToken(accessCodeResponse.RefreshToken)
 	config.SetToken(accessCodeResponse.AccessToken)
-	accId := getClaimFromToken(accessCodeResponse.IDToken, payloadAccountIdKey)
-	config.SetAccountId(accId)
 
-	auth0Id := getClaimFromToken(accessCodeResponse.AccessToken, "sub")
+	auth0ClientId := getClaimFromToken(accessCodeResponse.AccessToken, "sub")
```
Comment (georgievrado) [inline commands/login.go:68]: Can we name this idPClientID (IdentityProviderClientID) or something along the lines?

**Review by georgievrado — CHANGES_REQUESTED** [review]
Maybe we use less specific naming for the identity provider client ID. We do support other identity providers (different than auth0) in on-prem scenarios.

**Review by georgievrado — APPROVED** [review]
